[package]
name = "rustc-ja-wrapper"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
once_cell = "1.21.3"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
